### ISSUE TITLE
Motion notification through email

### ISSUE THREAD

**Issue by Quiwy** [jmichault/motioneye.eo#11]
Hi,
I'm trying to configure motioneye.eo to send email when through an ovh account with mx plan, but I don't manage to do it.

I've configured the notification with the following parameters : 
![image](https://user-images.githubusercontent.com/20048264/160193760-65d33ce5-19ad-42fa-83ca-6d156827a969.png) with the parameters coming from this page of documentation of ovh : https://docs.ovh.com/fr/emails/mail-mutualise-guide-configuration-dun-e-mail-mutualise-ovh-sur-linterface-de-gmail/ .

On thunderbird, the parameters with port 465 and TLS enabled.

I tried with port 587 too, TLS  enabled/disabled and nothing is working, I always have the message  `Notification email failed:Connection unexpectedly closed: timed out!`.

On journalctl I have the following error when pushing the `Test email button`

``` 
Mar 25 21:11:05 rpiserv meyectl[21797]:    ERROR: notification email test failed: Connection unexpectedly closed: timed out
Mar 25 21:11:05 rpiserv meyectl[21797]: Traceback (most recent call last):
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/lib/python3.7/smtplib.py", line 387, in getreply
Mar 25 21:11:05 rpiserv meyectl[21797]:     line = self.file.readline(_MAXLINE + 1)
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/lib/python3.7/socket.py", line 589, in readinto
Mar 25 21:11:05 rpiserv meyectl[21797]:     return self._sock.recv_into(b)
Mar 25 21:11:05 rpiserv meyectl[21797]: socket.timeout: timed out
Mar 25 21:11:05 rpiserv meyectl[21797]: During handling of the above exception, another exception occurred:
Mar 25 21:11:05 rpiserv meyectl[21797]: Traceback (most recent call last):
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/local/lib/python3.7/dist-packages/motioneye/handlers/config.py", line 614, in test
Mar 25 21:11:05 rpiserv meyectl[21797]:     subject=subject, message=message, files=[])
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/local/lib/python3.7/dist-packages/motioneye/sendmail.py", line 52, in send_mail
Mar 25 21:11:05 rpiserv meyectl[21797]:     conn = smtplib.SMTP(server, port, timeout=settings.SMTP_TIMEOUT)
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/lib/python3.7/smtplib.py", line 251, in __init__
Mar 25 21:11:05 rpiserv meyectl[21797]:     (code, msg) = self.connect(host, port)
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/lib/python3.7/smtplib.py", line 338, in connect
Mar 25 21:11:05 rpiserv meyectl[21797]:     (code, msg) = self.getreply()
Mar 25 21:11:05 rpiserv meyectl[21797]:   File "/usr/lib/python3.7/smtplib.py", line 391, in getreply
Mar 25 21:11:05 rpiserv meyectl[21797]:     + str(e))
Mar 25 21:11:05 rpiserv meyectl[21797]: smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
Mar 25 21:11:05 rpiserv meyectl[21797]:    ERROR: mjpg client timed out receiving data for camera 1 on port 8081

```
 
I had the same problem with the old motioneye, but just upgraded thinking it could be a problem with python2.
I tried with another serer of a friend and it's working.

I suspect something is going wrong on ovh side but I have no idea. Do you know if it could be something on motioneye.eo before I create a support request on their side?

Thank you for any help you could procure.

**Comment by jmichault** [comment]
Bonjour,
ta configuration me semble correcte.
Je n'ai pas de compte ovh pour pouvoir tester, mais en mettant ssl0.ovh.net , port 587, TLS activé, et des informations bidons pour le compte, j'obtiens dans les traces une erreur normale : «smtplib.SMTPAuthenticationError: (535, b'5.7.1 Authentication failed')».
Ton problème de timeout me fait penser à un blocage par un pare-feu chez toi, soit sur la machine qui héberge motioneye, soit sur ta box.
