### ISSUE TITLE
Exception in callback MjpgClient._on_connect

### ISSUE THREAD

**Issue by mkrsn** [jmichault/motioneye.eo#19]
Hi,

right after installing  and configuring motioneye.eo (22.4.1) i saw the following error.

```
ERROR: Exception in callback MjpgClient._on_connect(<Future finis...7f336dae47f0>>)
handle: <Handle MjpgClient._on_connect(<Future finis...7f336dae47f0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/base64.py", line 534, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/motioneye/lib/python3.10/site-packages/motioneye/mjpgclient.py", line 184, in _on_connect
    auth_header = utils.build_basic_header(self._username, self._password)
  File "/opt/motioneye/lib/python3.10/site-packages/motioneye/utils/__init__.py", line 282, in build_basic_header
    return 'Basic ' + base64.encodebytes(f'{username}:{password}').replace('\n', '')
  File "/usr/lib/python3.10/base64.py", line 551, in encodebytes
    _input_type_check(s)
  File "/usr/lib/python3.10/base64.py", line 537, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

p.s. thx for forking motioneye! :+1:

**Comment by MichaIng** [comment]
Fixed in original project this way: https://github.com/motioneye-project/motioneye/blob/2612b95/motioneye/utils/__init__.py#L281-L282

**Comment by mkrsn** [comment]
Thx for the hint. I've changed both lines but it looks like there are some more of this problem.

```
2022-08-26 16:16:45: [motioneye]    ERROR: Exception in callback MjpgClient._on_connect(<Future finis...7f16e0812e60>>)
handle: <Handle MjpgClient._on_connect(<Future finis...7f16e0812e60>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/motioneye/lib/python3.10/site-packages/motioneye/mjpgclient.py", line 186, in _on_connect
    b'GET / HTTP/1.0\r\nAuthorization: %s\r\nConnection: close\r\n\r\n'
TypeError: %b requires a bytes-like object, or an object that implements __bytes__, not 'str'
```

**Comment by MichaIng** [comment]
Just to rule it our, could you try to migrate to the other project (which includes all the localisation features and other enhancements from here, but some additional fixes, obviously): https://github.com/motioneye-project/motioneye/tree/dev#installation

**Comment by mkrsn** [comment]
I've switched to 0.43.0, as you recommended. Exceptions are gone.
