### ISSUE TITLE
Problème d'upload SFTP

### ISSUE THREAD

**Issue by cryptage21** [jmichault/motioneye.eo#5]
Hello,

Il me semble que l"on parle Français ici donc j'en profite.
J'ai un souci avec l'upload d'images SFTP lors d'une capture.

Les images ne sont jamais uploadées et dans les logs j'ai ceci : 

```
Feb 12 21:42:50 motioneye meyectl[6962]:    ERROR: failed to upload file "/motioneye/cam-3/2022-02-12/21-42-42.jpg" with service sftp: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
Feb 12 21:42:50 motioneye meyectl[6962]: Traceback (most recent call last):
Feb 12 21:42:50 motioneye meyectl[6962]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/uploadservices.py", line 1162, in upload_media_file
Feb 12 21:42:50 motioneye meyectl[6962]:     service.upload_file(target_dir, filename, camera_name)
Feb 12 21:42:50 motioneye meyectl[6962]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/uploadservices.py", line 98, in upload_file
Feb 12 21:42:50 motioneye meyectl[6962]:     data = f.read()
Feb 12 21:42:50 motioneye meyectl[6962]:   File "/usr/lib/python3.9/codecs.py", line 322, in decode
Feb 12 21:42:50 motioneye meyectl[6962]:     (result, consumed) = self._buffer_decode(data, self.errors, final)
Feb 12 21:42:50 motioneye meyectl[6962]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Le test de la configuration fonctionne parfaitement.
Je suis en Debian 11 et les options que j'utilise sont les suivantes : https://i.ibb.co/XFp4Vy1/meye2.jpg

Une idée ? 
Merci (et merci beaucoup pour le portage en Python3 !).

**Comment by jmichault** [comment]
Bonjour,
Apparemment quelques petits détails de portage en python3.
J'ai poussé une nouvelle version sur pypi.org, peux-tu mettre à jour et tester ?

Sinon, pas de problème pour l'installation ? (tu es le premier à me faire un retour)

**Comment by cryptage21** [comment]
Bonjour,

J'ai fait la MAJ et... ça fonctionne ! Merci. 
Il ne reste plus que le souci des images qui disparaissent par moment.

Concernant l'installation, je ne suis pas parti de zéro mais de la version MotionEye en Python2.7.

J'ai coupé MotionEye, fait le passage sur MotionEye.eo / Python3 et je n'ai eu qu'un seul petit bug d'affichage des miniatures qui n'apparaissaient pas dans la liste des vidéos (résolu par pip3 install pyffmpeg). 

Un grand merci d'avoir porté cet outil en Python3.
Je commençais à me dire qu'il allait falloir s'en séparer (mais pour quoi ? Il n'y a pas d'alternative aussi bien fichue). 

Maintenant qu'il est supporté en Python3, on sait maintenant qu'on devrait pouvoir upgrader vers les futures distrib et ça c'est top.
