### ISSUE TITLE
Perte fréquente de l'affichage des aperçus

### ISSUE THREAD

**Issue by cryptage21** [jmichault/motioneye.eo#6]
Hello,

J'ai un souci avec motioneye.eo.
Sur l'interface web, je perds régulièrement l'affichage des aperçus vidéos.

Dans les logs j'ai ceci (pour chaque caméra) : 

```
Feb 12 21:45:06 motioneye meyectl[6937]:    ERROR: mjpg client for camera 1 on port 8081 error: Stream is closed
Feb 12 21:45:06 motioneye meyectl[6937]: Traceback (most recent call last):
Feb 12 21:45:06 motioneye meyectl[6937]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/mjpgclient.py", line 246, in _on_before_content_length
Feb 12 21:45:06 motioneye meyectl[6937]:     future.result()
Feb 12 21:45:06 motioneye meyectl[6937]: tornado.iostream.StreamClosedError: Stream is closed
```

Et au niveau interface ça donne ceci : https://i.ibb.co/ng4L20h/meye.jpg

Les aperçus reviennent d'eux-mêmes après quelques secondes.

Une idée ? 
Merci :smile:

**Comment by jmichault** [comment]
J'ai le même problème.
Tout se passe comme si motioneye perdait la connexion avec motion.
Pourtant aucune erreur du coté de motion...
Pas d'idée pour l'instant...

**Comment by cryptage21** [comment]
Merci du retour ;)

**Comment by cryptage21** [comment]
J'ai fait un test avec la version 4.4 de Motion : résultat identique.

En activant le mode debug on obtient une information intéressante : 

```
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: mjpg client for camera 2 on port 8082 has been idle for 10 seconds, removing it
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: mjpg client for camera 1 on port 8081 has been idle for 10 seconds, removing it
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: mjpg client for camera 3 on port 8083 has been idle for 10 seconds, removing it
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: mjpg client for camera 4 on port 8084 has been idle for 10 seconds, removing it
Feb 15 23:44:13 motioneye meyectl[340388]:    ERROR: mjpg client for camera 2 on port 8082 error: Stream is closed
Feb 15 23:44:13 motioneye meyectl[340388]: Traceback (most recent call last):
Feb 15 23:44:13 motioneye meyectl[340388]:   File "/usr/local/lib/python3.9/dist-packages/motioneye/mjpgclient.py", line 246, in _on_before_content_length
Feb 15 23:44:13 motioneye meyectl[340388]:     future.result()
Feb 15 23:44:13 motioneye meyectl[340388]: tornado.iostream.StreamClosedError: Stream is closed
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: connection closed for mjpg client for camera 2 on port 8082
Feb 15 23:44:13 motioneye meyectl[340388]:    DEBUG: mjpg client for camera 2 on port 8082 removed
...
```

Le mode debug nous indique qu'on a ce mécanisme après 10 secondes d'inactivité.
C'est assez simple à vérifier : 
- Si on reste sur la page il ne se passe rien.
- Si on va sur un autre onglet par exemple au bout de 10 secondes on a ces messages.

De ma compréhension il coupe simplement le flux car il considère qu'il n'est plus utilisé.

Je ne suis pas développeur mais est-ce que les messages qu'on a ne seraient pas juste liés à une mauvaise gestion d'erreurs (qui n'en sont pas en réalité) dans mjpgclient.py ?
